### PR TITLE
added an if statement to list all the tasks

### PR DESCRIPTION
**Pull request by princedevc**
Please Merge PR

### CODE REVIEW

**Comment by keneNwobodo** [comment]
Please include screenshot of your code @princedevc

**Comment by princedevc** [comment]
there's no where to add image

**Comment by keneNwobodo** [comment]
Drag and drop the screenshot here.... It will generate a link or you, you can preview it by the side too. @princedevc

**Comment by princedevc** [comment]
https://res.cloudinary.com/dy8gpj7qo/image/upload/v1596709404/picture/Annotation_2020-08-06_110507_rm7euj.png

**Comment by princedevc** [comment]
had to upload to clodinary

**Comment by princedevc** [comment]
Annotation 2020-08-06 110507

ok it worked this time

**Pull request merged**
